version: '3.8'

services:
  backend:
    build: .
    container_name: kod-ureten-backend
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api/chat
    depends_on:
      - ollama
    volumes:
      - .:/app

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data:
